### ISSUE TITLE
Pip can't resolve dependencies

### ISSUE THREAD

**Issue by dantownsend** [adriangb/xpresso#83]
I'm having some trouble installing the following from a requirements file:

```
jinja2
piccolo[postgres]
piccolo_admin
xpresso
uvicorn
```

Pip can't resolve the dependencies and gets caught in an endless loop.

It only started today - I noticed because the CI started failing. I can't see anything in the latest Xpresso release which may have caused this.

Do you have any ideas?

**Comment by adriangb** [comment]
Weird. I have made some changes in the last week, but mostly loosening dependencies. I'll try this and report back.

**Comment by dantownsend** [comment]
@adriangb Thanks :)

**Comment by adriangb** [comment]
Worked fine in a colab notebook: https://colab.research.google.com/drive/1yojpO7dArlvlqh6GUay9NedM7AlSpH-g#scrollTo=wWX8WOo8FBzV

Could you post the Python/pip versions, and maybe point me to the failing CI runs and I can take a look at those as well?

Also I assume this works fine without Xpresso?

**Comment by adriangb** [comment]
I was able to reproduce now. I narrowed the issue down to:

```
piccolo_admin
starlette>=0.19.0
```

As of accf69a6c6fc3201deb7da94fea2282c1bd84579 Xpresso depends on `starlette>=0.19.0` so that we can use https://github.com/encode/starlette/pull/1435. I did this to avoid juggling compatibility; I thought there'd be no reason to install Xpresso along with  FastAPI. But it seems like [`piccolo_admin` depends on FastAPI](https://github.com/piccolo-orm/piccolo_admin/blob/f1b10458f3ffe14d0d872564ed15ad612934b8ef/requirements/requirements.txt#L7).

So there's two options here:

- Do compatibility stuff in Xpresso to support Starlette >= 0.17.1 (like we did before)
- Remove the direct dependency on FastAPI from Piccolo Admin. FastAPI pins specific Starlette versions, which makes it hard to maintain compatibility with it (I plan not to do this with Xpresso, but I just happened to update to >=0.19.0)

I'll look into the former, I don't think it will be too hard.

**Comment by dantownsend** [comment]
Thanks for looking into it. I've had problems too in the past with FastAPI version pinning a specific Starlette version.

I can't easily remove FastAPI from Piccolo Admin unfortunately.

I can temporarily disable the integration test, so there's no immediate pressure to get this fixed.

**Comment by adriangb** [comment]
I think I'll have a fix up in the next 15 min, let me try that before you disable the integration tests 😄

**Comment by dantownsend** [comment]
Awesome, thanks! 🚀

**Comment by adriangb** [comment]
All set! Build should be up on PyPi in the next 5 min

**Comment by dantownsend** [comment]
@adriangb Perfect, thank you!
